### ISSUE TITLE
Designers

### ISSUE THREAD

**Issue by Kupenya** [zuri-training/Auth-Wiki---Team-5#2]
Designers, can we  confirm that all these have been sorted out; research, moodboard, style guide, wireframe, high fidelity wireframe.

**Comment by Simply-stella** [comment]
> Designers, can we confirm that all these have been sorted out; research, moodboard, style guide, wireframe, high fidelity wireframe.

Yes, everything is sorted

**Comment by DesignHemperor** [comment]
Yes. Sorted!! 
Including lo-fi

**Comment by Remiayinla** [comment]
Yes, it has been sorted

**Comment by iamagchristian** [comment]
Yes

**Comment by olamideakintan** [comment]
they have been sorted

**Comment by Marquispaula** [comment]
On point

**Comment by wavytobi** [comment]
yes. its done!

**Comment by Martilda001** [comment]
> 

Yes, they have been sorted.

**Comment by Bolajii** [comment]
Yes, its done

**Comment by omonigho14** [comment]
Yep. Well done.
